%This script compares a 2D histogram generated by CMC with oen generated by
%MC. They each have the same random variate budget.

%increase N to increase the accuracy of the probabilities
N = 1*10^3;

fprintf('Running conditional Monte Carlo.\n\n')
[cmc_X, cmc_freq, cmc_total_rvs_used] = cmc(4, [200 100], N, 50);
fprintf('# of random variates used by CMC: %d\n', cmc_total_rvs_used);

fprintf('\nRunning classical Monte Carlo.\n\n')
[mc_X, mc_freq, mc_total_rvs_used] = mc(4, [200 100], cmc_total_rvs_used);
fprintf('# of random variates used by MC: %d\n', mc_total_rvs_used);

colormap(jet);

subplot(1, 2, 1);
imagesc(transpose(cmc_freq))
set(gca,'YDir','normal')
xticks(0:100:(length(mc_freq)-1))
yticks(0:100:(length(mc_freq)-1))
title('Conditional Monte Carlo');
xlabel('A(4)');
ylabel('B(4)');
axis square;

subplot(1, 2, 2);
imagesc(1, 1, transpose(mc_freq));
set(gca,'YDir','normal')
xticks(0:100:(length(mc_freq)-1))
yticks(0:100:(length(mc_freq)-1))
title('Classical Monte Carlo');
xlabel('A(4)');
ylabel('B(4)');
axis square;
